development:
    base_url: "http://localhost:3000"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://localhost:3000/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://localhost:3000/javascripts/better_kaltura_ads_nacamar.js"
    video_demo_1: "http://localhost:3000/videos/1"
    backend_key: "HxmfdCjuqozranEkavx6"
    backend_base_url: "http://localhost:8080"
    backend_video_submit_url: "/video/"# {"display_name":"Auf der Jahnhohe","account_id":1,"friendly_id":10001,"video_description":"","video_meta_tags":[""]}
    backend_video_analyze_url: "/video/?analyze="# {"friendly_id":10008,"quality":"basic"}
    backend_video_retrieve_url: "/video/?retrieve="# {"friendly_id":10001}

test:
    base_url: "http://107.20.141.244"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://107.20.141.244/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://107.20.141.244/javascripts/better_kaltura_ads_nacamar.js"
    keyword_data_dir: "/data/GoogleKeywordData07192011"
    video_demo_1: "http://107.20.141.244/videos/1"
    backend_key: "HxmfdCjuqozranEkavx6"

production:
    base_url: "http://www.bettersense.com"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://www.bettersense.com/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://www.bettersense.com/javascripts/better_kaltura_ads_nacamar.js"
    keyword_data_dir: "/data/GoogleKeywordData07192011"
    video_demo_1: "http://www.bettersense.com/videos/7"
    backend_key: "HxmfdCjuqozranEkavx6"
