development:
    base_url: "http://localhost:3000"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://localhost:3000/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://localhost:3000/javascripts/better_kaltura_ads_nacamar.js"
    video_demo_1: "http://localhost:3000/videos/1"
    backend_key: "HxmfdCjuqozranEkavx6"
    backend_base_url: "http://localhost:8080"
    backend_video_url: "/video/"
    backend_report_url: "/reports/"
    report_directory: "/reports/"
    upload_video_dir: "/public/system/vid_files/"
    upload_video_sub_dir: "/original/"
    poll_for_video_status_change_seconds: "30"
    send_video_to_backend_seconds: "15"
    delete_from_backend_seconds: "30"
    basic_cost_per_min: "2"
    premium_cost_per_min: "5"

test:
    base_url: "http://107.20.141.244"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://107.20.141.244/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://107.20.141.244/javascripts/better_kaltura_ads_nacamar.js"
    video_demo_1: "http://107.20.141.244/videos/1"
    backend_key: "HxmfdCjuqozranEkavx6"
    backend_base_url: "http://107.20.141.244:8080"
    backend_video_url: "/video/"
    backend_report_url: "/reports/"
    report_directory: "/reports/"
    upload_video_dir: "/public/system/vid_files/"
    upload_video_sub_dir: "/original/"
    poll_for_video_status_change_seconds: "30"
    send_video_to_backend_seconds: "15"
    delete_from_backend_seconds: "30"
    basic_cost_per_min: "2"
    premium_cost_per_min: "5"

production:
    base_url: "http://www.bettersense.com"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://www.bettersense.com/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://www.bettersense.com/javascripts/better_kaltura_ads_nacamar.js"
    video_demo_1: "http://www.bettersense.com/videos/7"
    backend_key: "HxmfdCjuqozranEkavx6"
    backend_base_url: "http://www.bettersense.com:8080"
    backend_video_url: "/video/"
    backend_report_url: "/reports/"
    report_directory: "/reports/"
    upload_video_dir: "/public/system/vid_files/"
    upload_video_sub_dir: "/original/"
    poll_for_video_status_change_seconds: "30"
    send_video_to_backend_seconds: "15"
    delete_from_backend_seconds: "30"
    basic_cost_per_min: "2"
    premium_cost_per_min: "5"
