development:
    base_url: "http://localhost:3000"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://localhost:3000/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://localhost:3000/javascripts/better_kaltura_ads_nacamar.js"
    keyword_data_dir: "/data/GoogleKeywordData07192011"

test:
    base_url: "http://www.bettersense.com:3000"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://www.bettersense.com:3000/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://www.bettersense.com:3000/javascripts/better_kaltura_ads_nacamar.js"
    keyword_data_dir: "/data/GoogleKeywordData07192011"

production:
    base_url: "http://www.bettersense.com:3000"
    processed_videos_dir: "/public/processedVideos"
    videos_dir: "/public/videos"
    kaltura_demo_path: "/app/views/kalturademo"
    kaltura_ads_js: "http://www.bettersense.com/javascripts/better_kaltura_ads.js"
    nacamar_js: "http://www.bettersense.com/javascripts/better_kaltura_ads_nacamar.js"
    keyword_data_dir: "/data/GoogleKeywordData07192011"
